name: ci

on:
#   push:
#     branches: [main]
#   pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: EED-Solutions/eed_gha_workflows/.github/actions/ruff@actions
        with:
          branch_name: ${{ github.ref_name }}
