name: update_eed_basic_utils

on:
  workflow_dispatch:

jobs:
  update_eed_basic_utils:
    uses: EED-Solutions/eed_gha_workflows/.github/workflows/callable_update_eed_basic_utils.yml@main
    with:
      package_name: eed_basic_utils
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
