name: update_eed_basic_utils

on:
  workflow_dispatch:

jobs:
  update_eed_basic_utils:
    uses: ./.github/workflows/callable_update_eed_basic_utils.yml
    with:
      package_name: eed_basic_utils
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
